### ISSUE TITLE
Code is unusable due to missing models (sintel.pytorch and stabNet.pth)

### ISSUE THREAD

**Issue by VisionaryMind** [Annbless/DUTCode#18]
So far, I am not seeing in the comments posted here that anyone has successfully run this code through to the end. I was able to make headway with an A100 40GB GPU and 600 2k images, however the code fails towards the end due to missing models. It is looking for both sintel.pytorch and stabNet.pth in the ckpt folder, both of which are not included via your download link. Please let us know where to find these models or if you would be able to update your archive to include them. Without them, it is not possible to run this code.

**Comment by VisionaryMind** [comment]
I have also confirmed that your Colab notebook is not functional. You provide Google Drive download links for the missing models there, but the links fail (as you have apparently deleted or removed them). So DUTCode is essentially broken at both the workstation and Colab levels. It will be interesting to test your code if, at some point, you will publish the models back to a public repository again. Thank you.

**Comment by Annbless** [comment]
Actually, the missing files are for using StabeNet and DIFRINT, not DUT models. You can simply comment out the commands for running the two models in the deploy file and only run the DUT models.

It seems that the links are not maintained in those repos. We will upload a backup file for reference soon.

**Comment by Annbless** [comment]
![image](https://user-images.githubusercontent.com/32097042/180680274-bbf95115-c493-46ae-b82c-63cc95542f7a.png)

We just run the code with DUT only in the colab, and it succeeds. However, due to the upgrade of PyTorch versions and the memory restriction strategy, we make some modifications:
1. cupy.util.memorize -> cupy.memorize: since there is no util module in upgraded PyTorch
2. we delete the number of images to 200 to adapt to the memory issue.

Hope it can help.

**Comment by VisionaryMind** [comment]
Thank you for the quick response. It appears the the DUT pipeline was not running because our images were sequences with 5 digits (e.g. 00001, 00002, etc.). Your code requires single digit sequences. Once fixing this formatting problem, the DUT pipeline runs without an issue.
